repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        files: ^med_crawler/
        types: [file, python]
        additional_dependencies: [mypy-extensions]
        args: [--ignore-missing-imports]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        files: ^(med_crawler|tests)/
        types: [file, python]
        entry: pytest tests/
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/ambv/black
    rev: "21.6b0"
    hooks:
      - id: black
        name: black
        files: ^(med_crawler|tests)/
        types: [file, python]
        entry: black cmed/
